//
//  Languages.swift
//  Pronounce
//
//  Created by asror on 05/02/26.
//

import Foundation

enum Languages: String, CaseIterable, Codable {
    case none = ""
    case arabic = "ar-SA"
    case banglaBangladesh = "bn-BD"
    case banglaIndia = "bn-IN"
    case czech = "cs-CZ"
    case danish = "da-DK"
    case germanAustria = "de-AT"
    case germanSwitzerland = "de-CH"
    case germanGermany = "de-DE"
    case greek = "el-GR"
    case englishAustralia = "en-AU"
    case englishCanada = "en-CA"
    case englishUK = "en-GB"
    case englishIreland = "en-IE"
    case englishIndia = "en-IN"
    case englishNewZealand = "en-NZ"
    case englishUS = "en-US"
    case englishSouthAfrica = "en-ZA"
    case spanishArgentina = "es-AR"
    case spanishChile = "es-CL"
    case spanishColombia = "es-CO"
    case spanishSpain = "es-ES"
    case spanishMexico = "es-MX"
    case spanishUS = "es-US"
    case finnish = "fi-FI"
    case frenchBelgium = "fr-BE"
    case frenchCanada = "fr-CA"
    case frenchSwitzerland = "fr-CH"
    case frenchFrance = "fr-FR"
    case hebrew = "he-IL"
    case hindi = "hi-IN"
    case hungarian = "hu-HU"
    case indonesian = "id-ID"
    case italianSwitzerland = "it-CH"
    case italianItaly = "it-IT"
    case japanese = "ja-JP"
    case korean = "ko-KR"
    case dutchBelgium = "nl-BE"
    case dutchNetherlands = "nl-NL"
    case norwegian = "no-NO"
    case polish = "pl-PL"
    case portugueseBrazil = "pt-BR"
    case portuguesePortugal = "pt-PT"
    case romanian = "ro-RO"
    case russian = "ru-RU"
    case slovak = "sk-SK"
    case swedish = "sv-SE"
    case tamilIndia = "ta-IN"
    case tamilSriLanka = "ta-LK"
    case thai = "th-TH"
    case turkish = "tr-TR"
    case chineseChina = "zh-CN"
    case chineseHongKong = "zh-HK"
    case chineseTaiwan = "zh-TW"
    
    static func from(_ detectedLanguage: String) -> Languages {
        return self.allCases.first { $0.rawValue.hasPrefix(detectedLanguage) } ?? .none
    }
    
    var displayName: String {
        switch self {
        case .none: return "None"
        case .arabic: return "Arabic (Saudi Arabia)"
        case .banglaBangladesh: return "Bangla (Bangladesh)"
        case .banglaIndia: return "Bangla (India)"
        case .czech: return "Czech"
        case .danish: return "Danish"
        case .germanAustria: return "German (Austria)"
        case .germanSwitzerland: return "German (Switzerland)"
        case .germanGermany: return "German (Germany)"
        case .greek: return "Greek"
        case .englishAustralia: return "English (Australia)"
        case .englishCanada: return "English (Canada)"
        case .englishUK: return "English (United Kingdom)"
        case .englishIreland: return "English (Ireland)"
        case .englishIndia: return "English (India)"
        case .englishNewZealand: return "English (New Zealand)"
        case .englishUS: return "English (United States)"
        case .englishSouthAfrica: return "English (South Africa)"
        case .spanishArgentina: return "Spanish (Argentina)"
        case .spanishChile: return "Spanish (Chile)"
        case .spanishColombia: return "Spanish (Colombia)"
        case .spanishSpain: return "Spanish (Spain)"
        case .spanishMexico: return "Spanish (Mexico)"
        case .spanishUS: return "Spanish (United States)"
        case .finnish: return "Finnish"
        case .frenchBelgium: return "French (Belgium)"
        case .frenchCanada: return "French (Canada)"
        case .frenchSwitzerland: return "French (Switzerland)"
        case .frenchFrance: return "French (France)"
        case .hebrew: return "Hebrew"
        case .hindi: return "Hindi"
        case .hungarian: return "Hungarian"
        case .indonesian: return "Indonesian"
        case .italianSwitzerland: return "Italian (Switzerland)"
        case .italianItaly: return "Italian (Italy)"
        case .japanese: return "Japanese"
        case .korean: return "Korean"
        case .dutchBelgium: return "Dutch (Belgium)"
        case .dutchNetherlands: return "Dutch (Netherlands)"
        case .norwegian: return "Norwegian"
        case .polish: return "Polish"
        case .portugueseBrazil: return "Portuguese (Brazil)"
        case .portuguesePortugal: return "Portuguese (Portugal)"
        case .romanian: return "Romanian"
        case .russian: return "Russian"
        case .slovak: return "Slovak"
        case .swedish: return "Swedish"
        case .tamilIndia: return "Tamil (India)"
        case .tamilSriLanka: return "Tamil (Sri Lanka)"
        case .thai: return "Thai"
        case .turkish: return "Turkish"
        case .chineseChina: return "Chinese (Simplified, China)"
        case .chineseHongKong: return "Chinese (Traditional, Hong Kong)"
        case .chineseTaiwan: return "Chinese (Traditional, Taiwan)"
        }
    }
}
